


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package design_1_axi4stream_vip_0_0_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter design_1_axi4stream_vip_0_0_VIP_INTERFACE_MODE     = 2;
      parameter design_1_axi4stream_vip_0_0_VIP_SIGNAL_SET         = 8'b10010011;
      parameter design_1_axi4stream_vip_0_0_VIP_DATA_WIDTH         = 24;
      parameter design_1_axi4stream_vip_0_0_VIP_ID_WIDTH           = 0;
      parameter design_1_axi4stream_vip_0_0_VIP_DEST_WIDTH         = 0;
      parameter design_1_axi4stream_vip_0_0_VIP_USER_WIDTH         = 1;
      parameter design_1_axi4stream_vip_0_0_VIP_USER_BITS_PER_BYTE = 0;
      parameter design_1_axi4stream_vip_0_0_VIP_HAS_TREADY         = 1;
      parameter design_1_axi4stream_vip_0_0_VIP_HAS_TSTRB          = 0;
      parameter design_1_axi4stream_vip_0_0_VIP_HAS_TKEEP          = 0;
      parameter design_1_axi4stream_vip_0_0_VIP_HAS_TLAST          = 1;
      parameter design_1_axi4stream_vip_0_0_VIP_HAS_ACLKEN         = 0;
      parameter design_1_axi4stream_vip_0_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi4stream_slv_agent #(design_1_axi4stream_vip_0_0_VIP_SIGNAL_SET, 
                        design_1_axi4stream_vip_0_0_VIP_DEST_WIDTH,
                        design_1_axi4stream_vip_0_0_VIP_DATA_WIDTH,
                        design_1_axi4stream_vip_0_0_VIP_ID_WIDTH,
                        design_1_axi4stream_vip_0_0_VIP_USER_WIDTH, 
                        design_1_axi4stream_vip_0_0_VIP_USER_BITS_PER_BYTE,
                        design_1_axi4stream_vip_0_0_VIP_HAS_ARESETN) design_1_axi4stream_vip_0_0_slv_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      design_1_axi4stream_vip_0_0_slv_t  design_1_axi4stream_vip_0_0_slv;
//      initial begin : START_design_1_axi4stream_vip_0_0_SLAVE
//        design_1_axi4stream_vip_0_0_slv = new("design_1_axi4stream_vip_0_0_slv", `design_1_axi4stream_vip_0_0_PATH_TO_INTERFACE);
//        design_1_axi4stream_vip_0_0_slv.start_slave();
//      end

endpackage : design_1_axi4stream_vip_0_0_pkg
