
set_property MARK_DEBUG false [get_nets system_i/v_tc_0_vtiming_out_HSYNC]
set_property MARK_DEBUG true [get_nets system_i/v_tc_0_vtiming_out_VBLANK]
set_property MARK_DEBUG true [get_nets system_i/rst_vid_clk_dyn_peripheral_aresetn]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0_locked]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0_vid_io_out_ACTIVE_VIDEO]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0_vid_io_out_HSYNC]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0_vid_io_out_VSYNC]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/underflow]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/overflow]
set_property MARK_DEBUG true [get_nets system_i/axi_vdma_0_M_AXIS_MM2S_TUSER]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[1]}]
set_property MARK_DEBUG true [get_nets system_i/axi_vdma_0_M_AXIS_MM2S_TVALID]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[2]}]
set_property MARK_DEBUG true [get_nets system_i/axi_vdma_0_M_AXIS_MM2S_TLAST]
set_property MARK_DEBUG true [get_nets system_i/axi_vdma_0_M_AXIS_MM2S_TREADY]

set_property MARK_DEBUG true [get_nets system_i/v_tc_0_vtiming_out_ACTIVE_VIDEO]
set_property MARK_DEBUG true [get_nets system_i/v_tc_0_vtiming_out_HBLANK]



set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_regs/reg_15/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~ "*ila_core_inst/use_probe_debug_circuit_2_reg*" && IS_SEQUENTIAL}]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_regs/reg_15/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~ "*ila_core_inst/en_adv_trigger_2_reg*" && IS_SEQUENTIAL}]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_regs/reg_1a/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~ "*ila_core_inst/en_adv_trigger_2_reg*" && IS_SEQUENTIAL}]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_in_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_in_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_in_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_in_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_out_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_out_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_out_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_out_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]

set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_regs/reg_15/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~ "*ila_core_inst/use_probe_debug_circuit_2_reg*" && IS_SEQUENTIAL}]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_regs/reg_15/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~ "*ila_core_inst/en_adv_trigger_2_reg*" && IS_SEQUENTIAL}]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_regs/reg_1a/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~ "*ila_core_inst/en_adv_trigger_2_reg*" && IS_SEQUENTIAL}]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_in_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_in_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_in_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_in_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_out_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_out_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_out_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_out_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]


set_property MARK_DEBUG true [get_nets system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TREADY]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[9]}]
set_property MARK_DEBUG true [get_nets system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TLAST]
set_property MARK_DEBUG true [get_nets system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TREADY]
set_property MARK_DEBUG true [get_nets system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TUSER]
set_property MARK_DEBUG true [get_nets system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TVALID]

set_property MARK_DEBUG true [get_nets system_i/rst_vid_clk_dyn_peripheral_reset]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[21]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[2]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[20]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[6]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[11]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[8]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[0]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[15]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[10]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[12]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[4]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[7]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[3]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[14]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[5]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[19]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[18]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[1]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[22]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[17]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[16]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[23]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[9]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[13]}]

set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_regs/reg_15/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~ "*ila_core_inst/use_probe_debug_circuit_2_reg*" && IS_SEQUENTIAL}]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_regs/reg_15/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~ "*ila_core_inst/en_adv_trigger_2_reg*" && IS_SEQUENTIAL}]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_regs/reg_1a/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~ "*ila_core_inst/en_adv_trigger_2_reg*" && IS_SEQUENTIAL}]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_in_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_in_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_in_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_in_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_out_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_out_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]
set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_out_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_out_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]

connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_clk_out2]]
connect_debug_port u_ila_1/clk [get_nets [list u_ila_1_PXL_CLK_O]]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out2]

set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[0]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[10]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[11]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[12]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[13]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[14]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[15]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[16]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[17]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[18]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[19]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[1]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[20]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[21]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[22]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[23]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[24]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[25]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[26]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[27]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[28]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[29]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[2]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[30]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[31]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[3]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[4]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[5]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[6]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[7]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[8]}]
set_property MARK_DEBUG false [get_nets {system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TDATA[9]}]
set_property MARK_DEBUG false [get_nets system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TLAST]
set_property MARK_DEBUG false [get_nets system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TUSER]
set_property MARK_DEBUG false [get_nets system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TVALID]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[0]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[10]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[11]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[12]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[13]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[14]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[15]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[16]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[17]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[18]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[19]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[1]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[20]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[21]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[22]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[23]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[24]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[25]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[26]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[27]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[28]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[29]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[2]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[30]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[31]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[32]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[33]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[34]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[35]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[36]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[37]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[38]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[39]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[3]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[4]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[5]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[6]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[7]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[8]}]
set_property MARK_DEBUG false [get_nets {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[9]}]
set_property MARK_DEBUG false [get_nets system_i/MIPI_CSI_2_RX_0_m_axis_video_TLAST]
set_property MARK_DEBUG false [get_nets system_i/MIPI_CSI_2_RX_0_m_axis_video_TREADY]
set_property MARK_DEBUG false [get_nets system_i/MIPI_CSI_2_RX_0_m_axis_video_TUSER]
set_property MARK_DEBUG false [get_nets system_i/MIPI_CSI_2_RX_0_m_axis_video_TVALID]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/clk_wiz_0/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 24 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[0]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[1]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[2]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[3]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[4]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[5]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[6]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[7]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[8]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[9]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[10]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[11]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[12]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[13]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[14]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[15]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[16]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[17]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[18]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[19]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[20]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[21]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[22]} {system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TDATA[23]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list system_i/video_dynclk/U0/PXL_CLK_O]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 24 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[0]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[1]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[2]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[3]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[4]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[5]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[6]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[7]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[8]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[9]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[10]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[11]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[12]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[13]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[14]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[15]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[16]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[17]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[18]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[19]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[20]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[21]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[22]} {system_i/v_axi4s_vid_out_0_vid_io_out_DATA[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 24 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[0]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[1]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[2]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[3]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[4]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[5]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[6]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[7]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[8]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[9]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[10]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[11]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[12]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[13]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[14]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[15]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[16]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[17]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[18]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[19]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[20]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[21]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[22]} {system_i/axi_vdma_0_M_AXIS_MM2S_TDATA[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list system_i/AXI_BayerToRGB_1_AXI_Stream_Master_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TUSER]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list system_i/AXI_GammaCorrection_0_AXI_Stream_Master_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list system_i/axi_vdma_0_M_AXIS_MM2S_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list system_i/axi_vdma_0_M_AXIS_MM2S_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list system_i/axi_vdma_0_M_AXIS_MM2S_TUSER]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list system_i/axi_vdma_0_M_AXIS_MM2S_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list system_i/v_axi4s_vid_out_0/overflow]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list system_i/rst_vid_clk_dyn_peripheral_aresetn]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list system_i/rst_vid_clk_dyn_peripheral_reset]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list system_i/v_axi4s_vid_out_0/underflow]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list system_i/v_axi4s_vid_out_0_locked]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list system_i/v_axi4s_vid_out_0_vid_io_out_ACTIVE_VIDEO]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list system_i/v_axi4s_vid_out_0_vid_io_out_HSYNC]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list system_i/v_axi4s_vid_out_0_vid_io_out_VSYNC]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list system_i/v_tc_0_vtiming_out_ACTIVE_VIDEO]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list system_i/v_tc_0_vtiming_out_HBLANK]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property port_width 1 [get_debug_ports u_ila_1/probe10]
connect_debug_port u_ila_1/probe10 [get_nets [list system_i/v_tc_0_vtiming_out_VBLANK]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets system_i/mm_clk_150]
