set_property MARK_DEBUG true [get_nets system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXACTIVEHS]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[7]}]
set_property MARK_DEBUG true [get_nets system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXSYNCHS]
set_property MARK_DEBUG true [get_nets system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXVALIDHS]
set_property MARK_DEBUG true [get_nets system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXACTIVEHS]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[7]}]
set_property MARK_DEBUG true [get_nets system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXSYNCHS]
set_property MARK_DEBUG true [get_nets system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXVALIDHS]
set_property MARK_DEBUG true [get_nets system_i/CSI2_0_m_axis_video_TVALID]
set_property MARK_DEBUG true [get_nets system_i/CSI2_0_m_axis_video_TUSER]
set_property MARK_DEBUG true [get_nets system_i/CSI2_0_m_axis_video_TLAST]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {system_i/CSI2_0_m_axis_video_TDATA[9]}]
set_property MARK_DEBUG true [get_nets system_i/CSI2_0_m_axis_video_TREADY]
connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_FCLK_CLK0]]


set_property MARK_DEBUG true [get_nets system_i/CSI2_0/U0/csi2_inst/crc_err]
set_property MARK_DEBUG true [get_nets system_i/CSI2_0/U0/csi2_inst/LLP_ECC_error_1]

set_property MARK_DEBUG false [get_nets system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_CL_STOPSTATE]
set_property MARK_DEBUG false [get_nets system_i/PixelClk_Generator/locked]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/locked]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/overflow]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[0]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[10]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[11]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[12]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[13]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[14]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[15]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[16]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[17]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[18]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[19]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[1]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[20]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[21]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[22]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[23]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[2]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[3]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[4]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[5]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[6]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[7]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[8]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[9]}]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/s_axis_video_tlast]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/s_axis_video_tready]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/s_axis_video_tuser]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/s_axis_video_tvalid]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/underflow]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/vid_active_video]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/vid_hblank]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/vid_vblank]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[18]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[2]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[21]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[3]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[24]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[0]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[6]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[8]}]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/vtg_active_video]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[22]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[19]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[12]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[20]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[25]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[14]}]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/vtg_hblank]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/vtg_vblank]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[9]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[4]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[16]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[1]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[11]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[23]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[17]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[5]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[10]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[13]}]
set_property MARK_DEBUG true [get_nets {system_i/v_axi4s_vid_out_0/status[7]}]
set_property MARK_DEBUG false [get_nets {system_i/v_axi4s_vid_out_0/status[26]}]
set_property MARK_DEBUG false [get_nets {system_i/v_axi4s_vid_out_0/status[29]}]
set_property MARK_DEBUG false [get_nets {system_i/v_axi4s_vid_out_0/status[30]}]
set_property MARK_DEBUG false [get_nets {system_i/v_axi4s_vid_out_0/status[28]}]
set_property MARK_DEBUG false [get_nets {system_i/v_axi4s_vid_out_0/status[31]}]
set_property MARK_DEBUG false [get_nets {system_i/v_axi4s_vid_out_0/status[27]}]
set_property MARK_DEBUG false [get_nets {system_i/v_axi4s_vid_out_0/status[15]}]
set_property MARK_DEBUG false [get_nets system_i/v_axi4s_vid_out_0/vid_io_out_ce]
set_property MARK_DEBUG false [get_nets system_i/v_axi4s_vid_out_0/vtg_ce]


set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/vtg_hsync]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/vtg_vsync]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/vid_hsync]
set_property MARK_DEBUG true [get_nets system_i/v_axi4s_vid_out_0/vid_vsync]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/MIPI_D_PHY_RX_0/U0/ClockLane/HSClockingX/CLK]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[0]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[1]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[2]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[3]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[4]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[5]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[6]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXDATAHS[7]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list system_i/PixelClk_Generator/inst/CLK_CORE_DRP_I/clk_inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 24 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[0]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[1]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[2]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[3]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[4]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[5]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[6]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[7]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[8]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[9]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[10]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[11]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[12]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[13]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[14]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[15]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[16]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[17]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[18]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[19]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[20]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[21]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[22]} {system_i/v_axi4s_vid_out_0/s_axis_video_tdata[23]}]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 24 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {system_i/CSI2_0_m_axis_video_TDATA[0]} {system_i/CSI2_0_m_axis_video_TDATA[1]} {system_i/CSI2_0_m_axis_video_TDATA[2]} {system_i/CSI2_0_m_axis_video_TDATA[3]} {system_i/CSI2_0_m_axis_video_TDATA[4]} {system_i/CSI2_0_m_axis_video_TDATA[5]} {system_i/CSI2_0_m_axis_video_TDATA[6]} {system_i/CSI2_0_m_axis_video_TDATA[7]} {system_i/CSI2_0_m_axis_video_TDATA[8]} {system_i/CSI2_0_m_axis_video_TDATA[9]} {system_i/CSI2_0_m_axis_video_TDATA[10]} {system_i/CSI2_0_m_axis_video_TDATA[11]} {system_i/CSI2_0_m_axis_video_TDATA[12]} {system_i/CSI2_0_m_axis_video_TDATA[13]} {system_i/CSI2_0_m_axis_video_TDATA[14]} {system_i/CSI2_0_m_axis_video_TDATA[15]} {system_i/CSI2_0_m_axis_video_TDATA[16]} {system_i/CSI2_0_m_axis_video_TDATA[17]} {system_i/CSI2_0_m_axis_video_TDATA[18]} {system_i/CSI2_0_m_axis_video_TDATA[19]} {system_i/CSI2_0_m_axis_video_TDATA[20]} {system_i/CSI2_0_m_axis_video_TDATA[21]} {system_i/CSI2_0_m_axis_video_TDATA[22]} {system_i/CSI2_0_m_axis_video_TDATA[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[0]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[1]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[2]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[3]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[4]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[5]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[6]} {system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXDATAHS[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXACTIVEHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXSYNCHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL0_RXVALIDHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXACTIVEHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXSYNCHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list system_i/MIPI_D_PHY_RX_0_D_PHY_PPI_DL1_RXVALIDHS]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 25 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {system_i/v_axi4s_vid_out_0/status[0]} {system_i/v_axi4s_vid_out_0/status[1]} {system_i/v_axi4s_vid_out_0/status[2]} {system_i/v_axi4s_vid_out_0/status[3]} {system_i/v_axi4s_vid_out_0/status[4]} {system_i/v_axi4s_vid_out_0/status[5]} {system_i/v_axi4s_vid_out_0/status[6]} {system_i/v_axi4s_vid_out_0/status[7]} {system_i/v_axi4s_vid_out_0/status[8]} {system_i/v_axi4s_vid_out_0/status[9]} {system_i/v_axi4s_vid_out_0/status[10]} {system_i/v_axi4s_vid_out_0/status[11]} {system_i/v_axi4s_vid_out_0/status[12]} {system_i/v_axi4s_vid_out_0/status[13]} {system_i/v_axi4s_vid_out_0/status[14]} {system_i/v_axi4s_vid_out_0/status[16]} {system_i/v_axi4s_vid_out_0/status[17]} {system_i/v_axi4s_vid_out_0/status[18]} {system_i/v_axi4s_vid_out_0/status[19]} {system_i/v_axi4s_vid_out_0/status[20]} {system_i/v_axi4s_vid_out_0/status[21]} {system_i/v_axi4s_vid_out_0/status[22]} {system_i/v_axi4s_vid_out_0/status[23]} {system_i/v_axi4s_vid_out_0/status[24]} {system_i/v_axi4s_vid_out_0/status[25]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list system_i/v_axi4s_vid_out_0/locked]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list system_i/v_axi4s_vid_out_0/overflow]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list system_i/v_axi4s_vid_out_0/s_axis_video_tlast]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list system_i/v_axi4s_vid_out_0/s_axis_video_tready]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list system_i/v_axi4s_vid_out_0/s_axis_video_tuser]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list system_i/v_axi4s_vid_out_0/s_axis_video_tvalid]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list system_i/v_axi4s_vid_out_0/underflow]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list system_i/v_axi4s_vid_out_0/vid_active_video]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property port_width 1 [get_debug_ports u_ila_1/probe10]
connect_debug_port u_ila_1/probe10 [get_nets [list system_i/v_axi4s_vid_out_0/vid_hblank]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe11]
set_property port_width 1 [get_debug_ports u_ila_1/probe11]
connect_debug_port u_ila_1/probe11 [get_nets [list system_i/v_axi4s_vid_out_0/vid_hsync]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe12]
set_property port_width 1 [get_debug_ports u_ila_1/probe12]
connect_debug_port u_ila_1/probe12 [get_nets [list system_i/v_axi4s_vid_out_0/vid_vblank]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe13]
set_property port_width 1 [get_debug_ports u_ila_1/probe13]
connect_debug_port u_ila_1/probe13 [get_nets [list system_i/v_axi4s_vid_out_0/vid_vsync]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe14]
set_property port_width 1 [get_debug_ports u_ila_1/probe14]
connect_debug_port u_ila_1/probe14 [get_nets [list system_i/v_axi4s_vid_out_0/vtg_active_video]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe15]
set_property port_width 1 [get_debug_ports u_ila_1/probe15]
connect_debug_port u_ila_1/probe15 [get_nets [list system_i/v_axi4s_vid_out_0/vtg_hblank]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe16]
set_property port_width 1 [get_debug_ports u_ila_1/probe16]
connect_debug_port u_ila_1/probe16 [get_nets [list system_i/v_axi4s_vid_out_0/vtg_hsync]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe17]
set_property port_width 1 [get_debug_ports u_ila_1/probe17]
connect_debug_port u_ila_1/probe17 [get_nets [list system_i/v_axi4s_vid_out_0/vtg_vblank]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe18]
set_property port_width 1 [get_debug_ports u_ila_1/probe18]
connect_debug_port u_ila_1/probe18 [get_nets [list system_i/v_axi4s_vid_out_0/vtg_vsync]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 1 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list system_i/CSI2_0/U0/csi2_inst/crc_err]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 1 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list system_i/CSI2_0_m_axis_video_TLAST]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 1 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list system_i/CSI2_0_m_axis_video_TREADY]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property port_width 1 [get_debug_ports u_ila_2/probe4]
connect_debug_port u_ila_2/probe4 [get_nets [list system_i/CSI2_0_m_axis_video_TUSER]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property port_width 1 [get_debug_ports u_ila_2/probe5]
connect_debug_port u_ila_2/probe5 [get_nets [list system_i/CSI2_0_m_axis_video_TVALID]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe6]
set_property port_width 1 [get_debug_ports u_ila_2/probe6]
connect_debug_port u_ila_2/probe6 [get_nets [list system_i/CSI2_0/U0/csi2_inst/LLP_ECC_error_1]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_2_FCLK_CLK1]
